const fs = require("node:fs");
const path = require("node:path");

const artifact = require("../artifacts/contracts/AgentSpendPolicy.sol/AgentSpendPolicy.json");
const out = path.resolve(__dirname, "../../server/src/chain/spend-policy-abi.ts");

fs.writeFileSync(
  out,
  "// Generated by contracts/scripts/export-abi.cjs from AgentSpendPolicy.sol — do not edit.\n" +
    `export const agentSpendPolicyAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`
);
console.log(`Wrote ${out}`);
